name: Build (wheel)
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: "ubuntu-latest" }
    env:
      WORKSPACE: "${{ github.workspace }}"
    defaults:
      run:
        shell: ${{ contains(matrix.os, 'windows') && 'pwsh' || 'bash -l {0}' }}
    steps:
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          environment-name: slimp
          create-args: python=3.11
      
      - name: Checkout latest revision
        uses: actions/checkout@v4
      
      - name: Set-up
        run: python .ci/build/conda.py ${{ env.MAMBA_EXE }}
      
      - name: Set CmdStan environment
        run: echo "CMDSTAN=${CONDA_PREFIX}/bin/cmdstan" >> ${GITHUB_ENV}
      
      - name: Build
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
      
      - name: Post build
        run: |
          python -m pip install dist/*.whl
          python -m unittest discover -s tests
